from django.urls import path
from .views import *

urlpatterns = [
path('accounts/login/',logoutNew),
    path('', loginPage),
    path('login',loginAndRedirect),
    path('logout',logoutNew),

    #reports
    # path('practo-report',practoReport),
    path('bigo-reports',bigoReport),
    path('aadya-reports',AadyaReport),
    path('aditya-birla-cellulose-reports',AdityaBirlaCelluloseReport),
    path('aditya-birla-toll-free-reports',AdityaBirlaTollFreeReport),
    path('aditya-birla-nps-reports',AdityaBirlaNPSReport),
    path('aditya-birla-retailer-calling-nps-reports',AdityaBirlaRetailerCallingReport),
    path('aditya-birla-website-enquiry-reports',AdityaBirlaWebsiteEnquiryReport),
    path('akdy-calls',AKDYcallsReport),
    path('avenue-living-communities',AvenueLivingCommunitiesReport),
    path('bhagyalaxmi-industries',BhagyalaxmiIndustriespractoReport),
    path('bng-vs-php',BNGvsPHP),
    path('career-transition-specialist',CareerTransitionSpecialist),
    path('citizen-capital',CitizenCapital),
    path('core-small-insurance-agency-inc',CoreySmallInsuranceAgencyInc),
    path('cross-tower',CrossTower),
    path('csc-service-works',CSCserviceWorks),
    path('daniel-wellington',DanielWellington),
    path('digital-signage',DigitalSignage),
    path('digital-swiss-gold',DigitalSwissGold),
    path('ee-hh-aaa',EEHHAAA),
    path('embassy-premium',EmbassyPremium),
    path('fame-house',FameHouse),
    path('fitness-mortgage',FitnessMortgage),
    path('genesis-acquisition',GenesisAccquisition),
    path('golden-eye-cctv',GoldenEyeCCTV),
    path('gubagoo',Gubagoo),
    path('hindalco',Hindalco),
    path('ilm',ILM),
    path('imaginarium',ImaginariumSolutionsLTD),
    path('imprint-plus',ImprintPlus),
    path('insalvage',Insalvage),
    path('kaapi-machines',KaapiMachines),
    path('lawoffice-m-geller',LawOfficesRobertMgeller),
    path('marcelo-perez',MarceloPerezStateFarm),
    path('marin-rv-storage',MarinRVstorage),
    path('medicare',MediCare),
    path('mob-twenty-two',MobileTwentyTwo),
    path('monster-lead',MonsterLead),
    path('movement-insurance',MovementInsurance),
    path('naffa-innovations',NaffaInnovations),
    path('new-dim-pharmacy',NewDimensionPharmacy),
    path('noom',Noom),
    path('printer-pix',PrinterPix),
    path('protostar',Protostar),
    path('rainbow-dia-lts',RainbowDiagnosticsLTS),
    path('sana-life-science',SanaLifeScience),
    path('saura-khalki-fashion',SaurabhaktiKhalkiFasion),
    path('schindler-media',SchindlerMedia),
    path('somethings-brewing',SomethingsBrewing),
    path('sterling-strategies-llc',SterlingStrategiesLLC),
    path('tanaor-jewelry-lsrael-ltd',TanaorJewelryIsraelLtd),
    path('tca-counseling-group',TCAcounselingGroup),
    path('tech-report',TechReport),
    path('us-jaclean-inc',USJacleanINC),
    path('ups-nps',UPSNPS),
    path('window-treatment-unlimited',WindowTreatmentUnlimited),
    path('winopoly', Winopoly),
    path('settings', change_password)
]